project_id = "nhoemjarkxqwruupqgyd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.resend-webhook]
verify_jwt = false

[functions.resend-email-events]
verify_jwt = false

[functions.send-email-ovh]
verify_jwt = false

[functions.form-submission-handler]
verify_jwt = false

[functions.nylas-email-callback]
verify_jwt = false

[functions.auto-email-sync]
verify_jwt = false
